### ISSUE TITLE
Custom Storage Initializer does not support S3 "path" addressing style

### ISSUE THREAD

**Issue by mginfn** [kubeflow/model-registry#1023]
**Describe the bug**

I'm running a Kubeflow instance and I have a model stored in the MinIO instance whose URI has been registered to the Model-Registry.
If I serve the model using the MinIO uri s3://mlpipeline/path/to/model it works.
If I serve the model using the Model-Registry uri "model-registry://model/1.0.0", the storage-initializer fails with error: 

- dial tcp: lookup mlpipeline.minio-service.kubeflow on 10.96.0.10:53: no such host

I assume it fails because the storage-initializer is using the "virtual" addressing style (prepending the bucket name to the host name), but the MinIO instance only supports the "path" addressing style (see [here](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html#addressing-style)).

**To Reproduce**

Store a model in the Kubeflow MinIO instance, and submit the following yaml:

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: model-dev
  namespace: my-namespace
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      modelFormat:
        name: pytorch
        version: "1"
      storageUri: "model-registry://model/1.0.0"
      # storageUri: s3://mlpipeline/path/to/model
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "1"
          memory: 1Gi
```

**Expected behavior**
The model is successfully served by KServe
