### ISSUE TITLE
K8s Job to sync models from one model storage location to another

### ISSUE THREAD

**Issue by Crazyglue** [kubeflow/model-registry#1108]
**Is your feature request related to a problem? Please describe.**

I would like to propose a feature to be able to copy one model from one storage location to another storage location, registering the model in the process, and generating a [ModelCar](https://kserve.github.io/website/latest/modelserving/storage/oci/) as a part of that process.

A common case is when a user wants all of their models to live in a centralized OCI-compliant storage layer (quay, self-hosted, etc), but they may not necessarily have all models they are interested currently in that storage layer.

For example, if you were interested in a model from a raw S3 URL or from HuggingFace, you might want to keep the base-model stored in your own OCI-compliant storage layer (or some other storage location). This also must be something that can be triggered from the UI, or independently of the UI.

**Describe the solution you'd like**

A K8s (vanilla) `Job` which will take a number of parameters and env vars, read those variables, and perform the synchronization job independently of the MR Service and MR UI.

This Job will initially be triggered by a UI action (to be done later), or a raw YAML/JSON k8s `Job` resource can be created out of band.

Later, if desired, we can enable the MR itself to expose an endpoint which can kick off these jobs in a structured way.

During this synchronization `Job`, various sanity checks will be performed to ensure the job can be completed, such as validating source and destination credentials, URIs, `modelName` (and other model-related params), etc.

In addition, it will generate a [ModelCar](https://kserve.github.io/website/latest/modelserving/storage/oci/) for that model to support model utilization in KServe, etc.

**Comment by Crazyglue** [comment]
For a first crack at what this k8s `Job` manifest might look like, I have a sample below. Note; the parameters shown are not an exhaustive list of parameters (notably, MR URL and Port are absent)

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: my-async-upload-Job
  namespace: model-registry # Or somewhere else
spec:
  template:
    spec:
      containers:
        - name: async-upload
          image: kubeflow/model-registry-async-job:latest
          command: ['/bin/sh', '-c', 'python', '/app/async_upload.py']
          args:
            - |
              # Upload params passed in here
              --source-uri=s3://my-bucket/my-model
              --source-type=s3
              --destination-uri=oci://my-registry/my-model
              --destination-type=oci
              --model-name=my-model
              --model-version=1.0.0
              --model-format=onnx
              --model-format-version=1.0
          restartPolicy: Never
          volumeMounts:
            - name: source-creds
              mountPath: "/mnt/source-creds"
              readOnly: true
            - name: destination-creds
              mountPath: "/mnt/destination-creds"
              readOnly: true
          env:
            # ---- Connection Secrets ----
            - name: SOURCE_SECRET_PATH
              value: "/mnt/source-secret" # <-- there will be a default, TBD where
            # or...
            - name: SOURCE__AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: ACCESS_KEY_ID
            # ...
            - name: DESTINATION__OCI_REGISTRY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oci-secret
                  key: OCI_REGISTRY_USERNAME
            # ...
            # ---- Model Params ----
            - name: MR__MODEL_NAME
              value: "my-model"
            - name: MR__MODEL_VERSION
              value: "1.0.0"
            - name: MR__MODEL_FORMAT
              value: "onnx"
            # ...
      
      volumes:
        - name: source-creds
          secret:
            secretName: my-source-secret
        - name: destination-creds
          secret:
            secretName: my-destination-secret
```

_Note_: Other [`Job` params](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#jobspec-v1-batch) like `suspend`, `backoffLimit`, etc are not present for brevity

---

The ENV vars supported will match 1-to-1 with the `args` that can be provided to the `command`. A short example of this equivalence between variable input is below:

Env to Param mapping

| Env Var Name                                 | `arg` Param              |
| ------------------------------------ | ------------------ |
| SOURCE__SECRET_PATH                   | source-secret-path      |
| DESTINATION__OCI_REGISTRY_USERNAME   | destination-oci-registry-username |
| MR__MODEL_NAME                       | model-name         |
| MR__MODEL_VERSION                    | model-version      |
| MR__MODEL_FORMAT                     | model-format       |

Examples

| Env Var                        | Param                   |
| --------------------------- | ----------------------- |
| MR__MODEL_NAME="my-model"   | --model-name "my-model" |
| MR__MODEL_VERSION="1.0.0"   | --model-version "1.0.0" |
| MR__MODEL_FORMAT="onnx"     | --model-format "onnx"   |
