### ISSUE TITLE
Provide ModelRegistry Custom Storage Initializer

### ISSUE THREAD

**Issue by lampajr** [kubeflow/model-registry#24]
**Is your feature request related to a problem? Please describe.**
As follow up of the KServe `ClusterStorageContainer` [0] exploration [1] I would suggest to include a ModelRegistry specific storage initializer as part of this repository.

_Benefits_:
* Showcase the model registry usage and motivation
* Encourages the adoption of model registry
* Make the model serving through model registry easier

_Limitations_:
* Feature not supported for model-mesh deployments [2]

> _NOTE_: the linked PoC was just a starting point, therefore there might be further improvements required, e.g., managing private locations.

[0] https://kserve.github.io/website/0.11/modelserving/storage/storagecontainers/
[1] https://github.com/lampajr/model-registry-storage-initializer
[2] https://github.com/kserve/modelmesh-serving/issues/471

**Describe the solution you'd like**
Provide a `Model Registry Custom Storage Initializer` container image that would allow users to serve ML models using model-registry custom URI formats like:
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "iris-model"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "model-registry://iris/v1"
```

The proposed implementation (based on the PoC) would manage URIs with this format: `model-registry://${REGISTERD_MODEL_NAME}/${MODEL_VERSION_NAME}`.

In order to make the new custom storage initializer image available, cluster admins should create a `ClusterStorageContainer` CR like the following one:
```yaml
apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
metadata:
  name: abc
spec:
  container:
    name: storage-initializer
    image: abc/model-registry-storage-initializer:latest
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: "1"
  supportedUriFormats:
    - prefix: model-registry://
```

**Describe alternatives you've considered**
n/a

**Additional context**
n/a
