### ISSUE TITLE
Add Model Catalog API to Model Registry

### ISSUE THREAD

**Issue by dhirajsb** [kubeflow/model-registry#702]
**Is your feature request related to a problem? Please describe.**
Several public ML and LLM model catalogs such as [Hugging Face](https://huggingface.co/) are now available with easily accessible opensource models. 
At present Kubeflow Model Registry has an API for registering and managing locally trained and published _Registered Models_. Also, users have to use a variety of different websites, UIs, or APIs to browse and discover foundation models in various catalogs and manually register them for deployment. 

**Describe the solution you'd like**
There is a need for a uniform and simple way to access various Model Catalogs hosting foundation models to allow users to easily discover and register models in a Model Registry for local training, enhancement, and serving. 
The implementation could start simple by allowing users to create a simple curated **model catalog source** that is backed by a yaml file. The yaml file could contain a list of high level foundation models metadata, some README text, and information about catalog model versions. 
In the future other catalog source implementations can be created to allow browsing Hugging Face, OpenAPI, etc. 

**Describe alternatives you've considered**
As an alternative, a common UI could be built that has adhoc client code to access different catalogs to browse and register models to a Kubeflow Model Registry. However, having a consolidated/common simple backend will make developing such a catalog browsing UI simpler in the future. 

**Additional context**
As an example, a simple API that exposes information about models such as the information provided in HuggingFace [modelcard](https://huggingface.co/docs/hub/en/model-cards), and also supports simple catalog model search by names, tags, etc. would be incredibly useful for Kubeflow users.

**Comment by dhirajsb** [comment]
@andreyvelich @thesuperzapper we're working on a design for a simple model catalog API wrapper for local and remote catalogs like Hugging Face. I'll add more details with diagram, etc. to this feature request tomorrow. 

We're hoping it's a valuable addition to Model Registry and helps make the entry point and user experience easier into Kubeflow Model Registry, especially for foundation models and LLMs.

**Comment by dhirajsb** [comment]
A proposed high level architecture would like below. 

A configmap can be used to configure a small amount of high level metadata about a collection of catalog sources, such as name, type, description, etc. Every catalog source may also include a secretName if credentials are required to connect to the catalog. E.g. HuggingFace could store API secret/token in a Kubernetes secret. 

Model registry would implement the logic to handle different catalog types, and process the catalog source information to fetch the catalog or create a remote connection to it. When Catalog API operations to list CatalogModels and CatalogModelRevisions are received, model registry will query the catalog source implementation logic to fetch the requested information. 

![Image](https://github.com/user-attachments/assets/6c1390e3-dcee-411e-90b9-4c68c08e10d9)

**Comment by pboyd** [comment]
Here is a draft spec for the model catalog YAML:

```
$id: https://kubeflow.org/model-registry/catalog.yaml
$schema: https://json-schema.org/draft/2020-12/schema
title: Model Catalog
type: object
properties:
  models:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
          description: Unique name for the model.
          example: ibm-granite/granite-3.1-8b-base
        provider:
          type: string
          example: IBM
        description:
          type: string
          description: Short description of the model.
        readmeLink:
          type: string
          description: URL to a text or markdown file with more information.
        language:
          type: array
          description: List of supported languages (https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes).
          items:
            type: string
          example:
            - en
            - es
            - cz
        license:
          type: string
          description: Short name of the model's license.
          example: apache-2.0
        licenseLink:
          type: string
          description: URL to the license text.
        libraryName:
          type: string
          example: transformers
        baseModel:
          type: array
          description: Reference to the base model (if any).
          items:
            type: object
            properties:
              catalog:
                type: string
                description: |-
                  Name of the catalog for an external base model. Omit for
                  models in the same catalog.
                example: huggingface.io
              repository:
                type: string
                description: |-
                  Name of the repository in an external catalog where the base
                  model exists. Omit for models in the same catalog.
                example: ibm-granite
              model:
                type: string
                example: granite-3.1-8b-base
        tags:
          type: array
          example:
            - language
          items:
            type: string
        tasks:
          type: array
          description: List of tasks the model is designed for.
          items:
            type: string
          example:
            - text-generation
        create:
          description: Creation time in milliseconds since epoch.
          type: integer
        lastUpdateTimeSinceEpoch:
          description: Last update time in milliseconds since epoch.
          type: integer
```

Here's a quick example for how this will look using a few IBM Granite models from Hugging Face:

```
models:
- name: ibm-granite/granite-3.1-8b-base
  provider: IBM
  description: A decoder-only code model designed for code generative tasks
  readmeLink: https://huggingface.co/ibm-granite/granite-3.1-8b-base/raw/main/README.md
  language: ["ar", "cs", "de", "en", "es", "fr", "it", "ja", "ko", "nl", "pt", "zh"]
  license: apache-2.0
  licenseLink: https://www.apache.org/licenses/LICENSE-2.0.txt
  libraryName: transformers
  tags:
    - language
    - granite-3.1
  tasks:
    - text-generation
  createTimeSinceEpoch: 1733514949000
  lastUpdateTimeSinceEpoch: 1734637721000
- name: ibm-granite/granite-3.1-8b-instruct
  provider: IBM
  description: A fine-tuned model based on Granite 8B Code Base
  readmeLink: https://huggingface.co/ibm-granite/granite-3.1-8b-instruct/raw/main/README.md
  language: ["ar", "cs", "de", "en", "es", "fr", "it", "ja", "ko", "nl", "pt", "zh"]
  license: apache-2.0
  licenseLink: https://www.apache.org/licenses/LICENSE-2.0.txt
  libraryName: transformers
  baseModel:
    - catalog: huggingface.io
      repository: ibm-granite
      model: granite-3.1-8b-base
  tags:
    - language
    - granite-3.1
  tasks:
    - text-generation
  createTimeSinceEpoch: 1733514949000
  lastUpdateTimeSinceEpoch: 1734637721000
```
