### ISSUE TITLE
How to pass the secret for model-registry csi in kserve

### ISSUE THREAD

**Issue by Yokesh-RS** [kubeflow/model-registry#745]
if the registered model has s3://<bucket>/modelname

I passed model-registry://<registered-modelname>/<version no>.

I have made a secret and service account to pass in the creds , however I end up in this error

 kubectl logs -n model-workloads gpt-2-modelregistry-predictor-00001-deployment-568cc645d4-zljks -c storage-initializer
Initializing, args: src_uri [model-registry://gpt-model/1] dest_path[ [/mnt/models]
Falling back to base url model-registry-service.kubeflow.svc.cluster.local:8080 for model registry service
 Download model indexed in model registry: modelName=, storageUri=model-registry://gpt-model/1, modelDir=/mnt/models
Parsed storageUri=model-registry://gpt-model/1 as: modelRegistryUrl=model-registry-service.kubeflow.svc.cluster.local:8080, registeredModelName=gpt-model, versionName=0xc0008142b0
 Fetching model: registeredModelName=gpt-model, versionName=0xc0008142b0
Fetching model version: model=&{0xc0008100c8 0xc0008123a0 <nil> gpt-model 0xc0008123b0 0xc000812390 0xc0008123c0 0xc0008123d0 0xc0008123e0}
 Fetching model artifacts: version=&{0xc00088c070 0xc000812200 <nil> 1 0xc000812230 0xc00088e1d0 3 0xc000812210 0xc00088e1e0 0xc000812220}
 Error downloading the model: unable to get batch objects RequestError: send request failed
caused by: Get "http://modelserving.10.10.10.10:12345/?prefix=gpt2": dial tcp: lookup modelserving.10.10.10.10 on 19.25.25.10:53: no such host

the s3 uri is s3://modelserving/gpt2

the modelregistry  uri is : model-registry://gpt-model/1

**Comment by Al-Pragliola** [comment]
A nice UX improvement, as already mentioned by @tarilabs in https://github.com/kserve/kserve/issues/3823
would be to be able to update the status of the inferenceservice using the storageinitializer result (among other things) instead of checking the logs of the initContainer

-- 

You can check the secrets passed to the initContainer at https://kserve.github.io/website/master/modelserving/storage/s3/s3/#create-s3-secret

For example

```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "iris-model"
spec:
  predictor:
    serviceAccountName: sa
    model:
      modelFormat:
        name: sklearn
      storageUri: "model-registry://iris/v1"
```

You just need to add the `serviceAccountName' which points to a service account in the same namespace as the inference service
